# Generated by Django 6.0.7 on 2026-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='dashboard.service'),
        ),
    ]
