# Generated by Django 6.0.7 on 2026-08-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_customer_appointment_customer'),
        ('dashboard', '0004_business_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_customers', to='dashboard.service'),
        ),
    ]
